name: Deploy RoastMyTaste API

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/erickkamii/roast-my-taste-api:latest .
          docker push ghcr.io/erickkamii/roast-my-taste-api:latest

  deploy-to-droplet:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/roastmytaste
            cd /opt/roastmytaste

            cat <<EOF > compose.yaml
            services:
              roast-api:
                image: ghcr.io/erickkamii/roast-my-taste-api:latest
                container_name: roast-api
                restart: unless-stopped
                ports:
                  - "8085:8080"
                env_file:
                  - .env
            EOF

            podman compose pull
            podman compose up -d
            
            podman image prune -f